GET http://localhost:3000/decks

###
GET http://localhost:3000/cards

###
//POST a new empty deck 
POST http://localhost:3000/deck/new 
Content-Type: application/json 

{
    "name": "first deck",
    "cards": []
}

###
//POST a new card 
POST http://localhost:3000/card/new
Content-Type: application/json 

{
    "front": "front",
    "back": "back"
    
}

###
//POST a new card and ASSIGN to a deck
POST http://localhost:3000/card/new/deck/649eca509874403ef532c030
Content-Type: application/json 

{
    "front": "front",
    "back": "back"
}

###
//PUT an existing card to a certain deck
POST http://localhost:3000/deck/649ec7c440cf6c027c977a9c/card/649ec7c140cf6c027c977a99


###
DELETE http://localhost:3000/deck/delete/649ec7b740cf6c027c977a97

###
DELETE http://localhost:3000/card/delete/649ebf9af69c97c6eff84d0f


###
//DELETE a card from a certain deck
DELETE http://localhost:3000/deck/649ebf97f69c97c6eff84d0d/card/649ebf9af69c97c6eff84d0f


